# Registra la capa ante BitBake
BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "control-acceso"
BBFILE_PATTERN_control-acceso = "^${LAYERDIR}/"
BBFILE_PRIORITY_control-acceso = "10"

# No depende de meta-raspberrypi a propósito: así la misma capa sirve para QEMU
LAYERDEPENDS_control-acceso = "core openembedded-layer multimedia-layer"
LAYERSERIES_COMPAT_control-acceso = "scarthgap"
